### ISSUE TITLE
Is this intentional?

### ISSUE THREAD

**Issue by Psychodeus** [glisco03/conjuring#36]
The power of Soul alloy shovel (Right click) is enabled by default, even without toggling the tool mode I can use the power.
Isn't it supposed to be toggeled first? For safety reason? And making path by just normal walking (No sneak)?

Ver: [1.18+] Conjuring 2 - 1.0.20

**Comment by gliscowo** [comment]
Hey, while this is in fact intentional I can see why it would cause confusion. The reasoning behind why most tool abilities are locked behind the mode toggle is that they can be quite destructive, like how the Hatchet could conceivably destroy half your house accidentally. The magnet of the Shovel posses very little destructive potential and and thus it's enabled by default. I do however see your point about being able to make paths without sneaking, plus it's most likely better for consistency reasons. While I would like to change it, I feel like at this point with a large existing playerbase that would probably cause more confusion than it avoids, so at least for the time being it'll stay as-is
Cheers
