### ISSUE TITLE
Lever defected on conjurer

### ISSUE THREAD

**Issue by Psychodeus** [glisco03/conjuring#37]
> I'm using Minecraft Java 1.18.1
> Conjuring v1.0.20+1.18

Lever defected when placed on **conjurer** but fine when placed on another block.

![2022-05-07_00 57 51](https://user-images.githubusercontent.com/93028949/167178599-9af43426-4941-4702-aa55-c45341ba721d.png)

![2022-05-07_00 58 02](https://user-images.githubusercontent.com/93028949/167178581-faf2fad8-3a3a-48b0-9a70-d5f8011cb00e.png)

![2022-05-07_00 58 13](https://user-images.githubusercontent.com/93028949/167178571-3e7dc3ec-a7dd-4363-a2d2-8c35de7e3cee.png)

**Comment by gliscowo** [comment]
You are clearly using more mods than just Conjuring, as well as a resource pack. All of this is important information without which it'll be basically impossible for us to track this issue down
Cheers

**Comment by Psychodeus** [comment]
![image](https://user-images.githubusercontent.com/93028949/167207882-94c4e464-4cf9-4216-aaa1-c05318b9cd92.png)
![image](https://user-images.githubusercontent.com/93028949/167207926-0631074f-525c-44a3-b127-bffdfe6119e0.png)

Are you sure? o_o')

**Comment by Noaaan** [comment]
Tested this in a larger pack with the same version and found no issue disabling spawners. 
In your image it seems that your lever is floating? It does not look like it is powering the Conjurer at all. 
Due to inactivity and the inability to re-produce this issue, I am closing it. 
![image](https://user-images.githubusercontent.com/4163353/173163256-43ab2023-a4a0-41d4-a0af-a1b723d7c871.png)
