### ISSUE TITLE
JourneyMap Beacons / Pips are removed when this mod is enabled.

### ISSUE THREAD

**Issue by coldReactive** [glisco03/conjuring#61]
For whatever reason, Conjuring disables the visibility of Pips and Beacons for the JourneyMap mod.

[latest.log](https://github.com/wisp-forest/conjuring/files/13454740/latest.log)

Video Evidence of the issue: https://www.youtube.com/watch?v=TDlH89kbFpY

**Comment by mysticdrew** [comment]
JourneyMap dev here. 
If you need any assistance in resolving the issue, let me know.

**Comment by gliscowo** [comment]
Thanks for reporting this! The problem was actually being caused by [Lavender](https://github.com/wisp-forest/lavender), the library used for the Enchiridion. I've now published a fix for [1.20.1](https://modrinth.com/mod/conjuring/version/1.0.29+1.20) and [1.20.2](https://modrinth.com/mod/conjuring/version/1.0.29+1.20.2)

Cheers

**Comment by mysticdrew** [comment]
Thanks for fixing this. 
I did notice during my testing that the current indev version of JourneyMap that is not released yet which a lot of the rendering code as been rewritten it worked correctly. But it is not even close to being ready for release.
